# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
[wallpaper]
custom_paths = [
    "$XDG_PICTURES_DIR",
    "~/Downloads",
] # List of paths to search for wallpapers
